import math
import turtle
turtle.bgcolor("black")
turtle.shape("turtle")
turtle.speed(5000)
turtle.fillcolor("brown")
turtle.penup()
turtle.goto(0, -200)
turtle.pendown()
turtle.setheading(90)
turtle.fillcolor("green") 
turtle.begin_fill()
turtle.forward(200)
turtle.left(90)
turtle.forward(20)
turtle.left(90)
turtle.forward(500)
turtle.end_fill()
turtle.penup()
turtle.goto(0, -180)
turtle.fillcolor("#8B4513")  
turtle.begin_fill()
turtle.circle(0)
turtle.end_fill()
start_color = (255, 255, 0)
end_color = (255, 165, 0)
phi = 137.508 * (math.pi / 180.0)
for i in range(120):
    r = 4 * math.sqrt(i)
    theta = i * phi
    x = r * math.cos(theta)
    y = r * math.sin(theta)
    turtle.penup()
    turtle.goto(x, y)
    turtle.setheading(i * 137.508)
    turtle.pendown()
    if i < 86:
        turtle.stamp()
    else:
        step = (i - 86) / 34
        color = [int(start + step * (end - start)) for start, end in zip(start_color, end_color)]
        turtle.pencolor(color[0] / 255, color[1] / 255, color[2] / 255) 
        turtle.fillcolor(color[0] / 255, color[1] / 255, color[2] / 255) 
        turtle.begin_fill()
        turtle.right(20)
        turtle.forward(70)
        turtle.left(40)
        turtle.forward(70)
        turtle.left(140)    
        turtle.forward(70)
        turtle.left(40)
        turtle.forward(70)
        turtle.end_fill()
turtle.penup()
turtle.goto(0, 200)  
turtle.color("white")  
turtle.write("Una flor para una hermosa como tú", align="center", font=("Times New Roman", 8, "italic"))
turtle.goto(0, -250)
turtle.write("\n   chochito          ", align="center", font=("Times New Roman", 8 , "italic"))
turtle.hideturtle()
turtle.exitonclick()
    